# Generated by Django 4.0.4 on 2022-04-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=60)),
                ('home_number', models.CharField(max_length=8)),
                ('postal_code', models.CharField(max_length=6)),
                ('telephone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Printout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_color', models.BooleanField(default=True)),
                ('is_gloss', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('image_file', models.ImageField(upload_to='user_prints')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=200)),
                ('delivery_method', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='print4you.address')),
                ('printout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='print4you.printout')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
