# Generated by Django 4.0.4 on 2022-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print4you', '0001_init_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='printout',
            name='size',
            field=models.CharField(default='10x15', max_length=7),
            preserve_default=False,
        ),
    ]
