# Generated by Django 4.0.4 on 2022-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print4you', '0002_add_size_in_printout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('poczta', 'Przesyłka pocztowa'), ('kurier', 'Przesyłka kurierska'), ('paczkomat', 'Odbiór w paczkomacie')], default='poczta', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('przelew', 'Przelew'), ('karta', 'Karta kredytowa/debetowa'), ('blik', 'BLIK')], default='przelew', max_length=30),
        ),
        migrations.AlterField(
            model_name='printout',
            name='size',
            field=models.CharField(choices=[('10x15', '10x15'), ('13x18', '13x18'), ('15x21', '15x21'), ('20x25', '20x25'), ('A4', 'A4'), ('A3', 'A3'), ('50x60', '50x60'), ('100x50', '100x50'), ('100x70', '100x70'), ('160x60', '160x60'), ('140x100', '140x100'), ('118 1mb', '118 1mb')], default='1', max_length=7),
        ),
    ]
