# Generated by Django 4.0.4 on 2022-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print4you', '0003_added_choice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printout',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
